#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 15 13:13:26 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=ComplementaryReimagined_r5.6.1.zip
enableShaders=false
