onCull = false
MaxEntityEntities = 160
qualityModes = "NORMAL"
RenderWeather = "CLOSE"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 65.719
onGui = true
GuiRXTX = true
GuiFPS = true
GuiCPU = true
GuiGPU = true
GuiRAM = true
GuiEntityCount = true
GuiPlayerPos = true
GuiServer = true
GuiCameraTarget = true
Mood = false
MaxParticleDistance = 86
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 32
GuiViewMode = "EMPTY"
MinDistance = 6
EntityDistance = 64
TickPerformance = true
ParticlePerformance = false
EntityPerformance = true
EntityViewDebug = false
ParticleCountLimit = 8192
BlockBreakParticle = true
AsyncCompute = true
