
["Extended Datapacks"]
	#Determine how Epic Fight EDP will handle errors.
	#
	#CATCH: Catches errors, preventing the game from closing if an error occurs. It does not provide any debugging data.
	#
	#EXCEPTION: Closes the game immediately upon an error. The closure is immediate and provides debugging data.
	#Allowed Values: RESIST, ABORT
	fatalEpicFightEDPRuntimeHandler = "RESIST"

["Extended Datapacks (Epic Fight Combat -/- Charged Attacks)"]
	#Determine whether or not to use weight when executing a charged attack,
	#this means that as the player's weight increases, the stamina consumption per charged attack also increases. 
	useStaminaInChargedAttacks = true
	#Determine the value by which the stamina consumption result will be divided; this is a control factor.
	#The higher the value, the less stamina will be used, and the lower the value, the more realistic the value will be
	#(i.e., there is a greater demand for stamina).
	#Range: 1.0 ~ 4.0
	setWeightDivisorValue = 2.3

