onCull = false
MaxEntityEntities = 128
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = ["minecraft:player"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 94.214
onGui = true
GuiRXTX = true
GuiFPS = true
GuiCPU = true
GuiGPU = true
GuiRAM = true
GuiEntityCount = true
GuiPlayerPos = true
GuiServer = true
GuiCameraTarget = false
Mood = false
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "EMPTY"
MinDistance = 5
EntityDistance = 64
TickPerformance = true
ParticlePerformance = false
EntityPerformance = true
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = false
