config_version = 1
mod_version = "2.5.2"


[overlay]
    #Enable sleep overlay. Range: true | false. Default: true
    sleepOverlayEnabled = true

    #Overlay darkness. Range: 0.0 to 1.0. Default: 0.35
    sleepOverlayDarknessMultiplier = 0.35



[chat]
    #Chat text opacity multiplier. Range: 0.0 to 1.0. Default: 0.5
    sleepChatTextOpacityMultiplier = 0.5

    #Chat background opacity multiplier. Range: 0.0 to 1.0. Default: 0.4
    sleepChatBackgroundOpacityMultiplier = 0.4

    #Global chat opacity multiplier. Range: 0.1 to 2.0. Default: 1.0
    sleepChatOpacityMultiplier = 1.0

    #Max chat lines in bed chat. Range: integer 0 to 12. Default: 4
    sleepChatMaxLines = 4



[camera]
    #Camera tilt angle. Range: -90.0 to 90.0. Default: 10.0
    sleepCameraTiltDegrees = 10.0



[advanced]
    #Replay compatibility mode. Range: true | false. Default: true
    replayCompatibilityEnabled = true

    #Verbose debug logs. Range: true | false. Default: false
    debugLogsEnabled = false
