
[dreamwoods_biome_colors]

	#Configure which color properties are enabled for each Dreamwoods biome
	[dreamwoods_biome_colors.alpine_fields]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.arid_plains]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.autumnal_hills]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.autumnal_wood]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.azure_cove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.bayou]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.blooming_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.boskage]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.calcite_plateau]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.elder_woods]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.fall_fruitfull_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.fall_snowy_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.fir_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.flooded_rainforest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.flowering_fields]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.frozen_shore]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.golden_aspen_spinney]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.grassy_badlands]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.grassy_shore]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.gravel_beach]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.grim_woods]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.ice_abyss]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.ice_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.jungle_bushland]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.jungle_shore]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.lush_grassland]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.lush_meadow]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.moor]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.morass]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.northern_swamp]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.old_growth_swampland]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.poplar_fields]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.poplar_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.poplar_slopes]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.prairie]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.redwood_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.roofed_tropical_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.ruby_maple_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.fairy_garden]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.savanna_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.seasonal_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.seasonal_taiga]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.snowy_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.snowy_pinelands]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.spinney]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.spruce_lowlands]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.spruce_slopes]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.lush_coniferous_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.temperate_hemlock_rainforest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.thaumic_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.thermal_springs]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.tropical_river]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.tundra]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.twilight_wetlands]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.volcano_fields]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.weeping_grove]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.wet_larch_forest]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.white_shore]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

	[dreamwoods_biome_colors.wooded_slopes]
		#Enable custom sky color
		sky_color = true
		#Enable custom fog color
		fog_color = true
		#Enable custom water color
		water_color = true
		#Enable custom water fog color
		water_fog_color = true

